version: "3"

services:
  api-ts:
    build:
      context: ./docker/api-ts
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./api-ts:/app
    ports:
      - 3010:3000
    tty: true
    depends_on:
      - db
  db:
    restart: always
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
